% c03_syllable_call.m
% Example calls for c03_syllable_region_stats.

plot_syllables = [0, 1, 2, 3, 4];
plot_syllables = [18, 20, 29, 22, 14, 16];
plot_syllables = most_common_motifs_all(1:95); plot_syllables = setdiff(plot_syllables, [29, 85, 75, 91, 86, 68, 69, 83, ]);
plot_syllables = motifs_second_highest_at_least_200;
plot_syllables = setdiff(plot_syllables, [29, 85, 75, 91, 86, 68, 69, 83, ]);

pre_window = [-1.5, -0.5];
post_window = [0, 1];
analysis_parts = {'lme'};  % {'pooled'}, {'lme'}, or {'pooled', 'lme'}
% analysis_modes = 'all_data';
analysis_modes = 'trial_outside_trial';
plot_p_values_corr = true;
show_sorted_p_values = false;  % false: 3 sorted bars; true: 5-row comparison view
require_complete_animal_days = false;

%--------------------------------------------------------------------------
% All data only

stats_out_all_data = c03_syllable_region_stats(all_data, ...
    'syllables', plot_syllables, ...
    'analysis_modes', analysis_modes, ...
    'analysis_parts', analysis_parts, ...
    'plot_p_values_corr', plot_p_values_corr, ...
    'show_sorted_p_values', show_sorted_p_values, ...
    'require_complete_animal_days', require_complete_animal_days, ...
    'pre_window', pre_window, ...
    'post_window', post_window);
%%
%--------------------------------------------------------------------------
% Trial and outside-trial split only

stats_out_trial_outside = c03_syllable_region_stats(all_data, ...
    'syllables', plot_syllables, ...
    'analysis_modes', {'trial_outside_trial'}, ...
    'analysis_parts', analysis_parts, ...
    'plot_p_values_corr', plot_p_values_corr, ...
    'show_sorted_p_values', show_sorted_p_values, ...
    'require_complete_animal_days', require_complete_animal_days, ...
    'pre_window', pre_window, ...
    'post_window', post_window);

%--------------------------------------------------------------------------
% All data plus trial and outside-trial split

stats_out_all_modes = c03_syllable_region_stats(all_data, ...
    'syllables', plot_syllables, ...
    'analysis_modes', {'all_data', 'trial_outside_trial'}, ...
    'analysis_parts', analysis_parts, ...
    'plot_p_values_corr', plot_p_values_corr, ...
    'show_sorted_p_values', show_sorted_p_values, ...
    'require_complete_animal_days', require_complete_animal_days, ...
    'pre_window', pre_window, ...
    'post_window', post_window);

%--------------------------------------------------------------------------
% First analysis only: pooled permutation screens

stats_out_pooled_only = c03_syllable_region_stats(all_data, ...
    'syllables', plot_syllables, ...
    'analysis_modes', {'all_data', 'trial_outside_trial'}, ...
    'analysis_parts', {'pooled'}, ...
    'require_complete_animal_days', require_complete_animal_days, ...
    'pre_window', pre_window, ...
    'post_window', post_window);

%--------------------------------------------------------------------------
% Second analysis only: LME screen and detailed LME-ranked follow-up figures

stats_out_lme_only = c03_syllable_region_stats(all_data, ...
    'syllables', plot_syllables, ...
    'analysis_modes', {'all_data', 'trial_outside_trial'}, ...
    'analysis_parts', {'lme'}, ...
    'plot_p_values_corr', plot_p_values_corr, ...
    'show_sorted_p_values', show_sorted_p_values, ...
    'require_complete_animal_days', require_complete_animal_days, ...
    'pre_window', pre_window, ...
    'post_window', post_window);

%--------------------------------------------------------------------------
% Post-onset activity only, with no pre-window subtraction

stats_out_post_only = c03_syllable_region_stats(all_data, ...
    'syllables', plot_syllables, ...
    'analysis_modes', {'all_data', 'trial_outside_trial'}, ...
    'analysis_parts', analysis_parts, ...
    'plot_p_values_corr', plot_p_values_corr, ...
    'show_sorted_p_values', show_sorted_p_values, ...
    'require_complete_animal_days', require_complete_animal_days, ...
    'pre_window', [], ...
    'post_window', [0, 1.5]);
